### PR TITLE
Support non-standard error fields

### PR DESCRIPTION
**Pull request by lucasmarshall**
The GitHub GraphQL API errors include a `type` field in their errors, which is missing on the `GraphQLError` class. This causes a `TypeError` when getting a response from the API that includes errors.

There didn't seem to be any tests for this module. I can add one for this case if you like, but I wouldn't have the time right now to add tests for other error cases.

### CODE REVIEW

**Comment by lucasmarshall** [comment]
@abn would you mind taking a look since it seems you were the author of this?

Thanks!

**Comment by abn** [comment]
@lucasmarshall thank you for the PR, much appreciated. 

Looking at the current active version of the spec, it discourages extra properties in errors. While, GitHub's response is valid, afaict "type" is not a property mentioned in the spec. So, I am inclined towards maybe adding a more generic fix in order to support extra properties dynamically as well as the upcoming `extensions` property. 

https://spec.graphql.org/draft/#sec-Errors

**Comment by lucasmarshall** [comment]
> @lucasmarshall thank you for the PR, much appreciated.
> 
> Looking at the current active version of the spec, it discourages extra properties in errors. While, GitHub's response is valid, afaict "type" is not a property mentioned in the spec. So, I am inclined towards maybe adding a more generic fix in order to support extra properties dynamically as well as the upcoming `extensions` property.
> 
> https://spec.graphql.org/draft/#sec-Errors

Thanks for the feedback. I've updated the PR. We now will be stashing "unknown" fields in the errors in the `extensions` field.

**Comment by lucasmarshall** [comment]
> We might be able to do something a bit better. As mentioned before, extra properties are still valid. I reckon we should not transform it. It might be a good idea to love the instantiation logic into a class method in `GraphQLError`, something like `def load(cls, data: Dict[str, Any]) -> GraphQLError:`. This way we keep this logic contained
> 
> We could make use of `dataclasses.fields` and `dataclasses.make_dataclass` to create an inherited `CustomGraphQLError(GraphQLError)` instance at runtime as shown [here](https://stackoverflow.com/a/52536584/1210349).
> 
> In the case of GitHub we will end up with a `CustomGraphQLError` that contains the all of the known fields from the base dataclass and the additional ones like `type`.

Thanks for the feedback. I've modified the error class to have a factory method that will create a new instance of a custom class if an unknown field is in the error response, as requested.

**Comment by abn** [comment]
@lucasmarshall thank you implementing this. :rocket:

**Pull request merged**
