### PR TITLE
Socks support

### PR DESCRIPTION
**Pull request by temrix**
This pull request includes support for socks5 proxies.

The `brook` server that speaks socks5 is added to the Docker testing environment so the functionality can be tested. The newly written test is set to the localhost IP `127.0.0.1` which should work as it is the externally mapped port from Docker, however it doesn't on my end. Workaround: The command `docker network inspect aiographql-client_default` lists the IP addresses involved and one could replace `127.0.0.1` in the test with the IP in the output of `IPAM.Config.Gateway`.

An additional linting environment is added to `tox.ini`.

### CODE REVIEW

**Comment by abn** [comment]
@temrix thank you for contributing :heart: 

So, with 1.x (now in pre-release) we have changed a lot of how the client is structured. This also introduces the ability to provide a custom session for usage with aiohttp. So you can, in-effect use a socks-proxy if required.

I have just added documentation for this at https://aiographql-client.readthedocs.io/en/latest/examples.html#using-behind-sock-proxies

Let me know if I missed something.

**Comment by abn** [comment]
And if you are interested, the reason why the compose setup was not working is because for brook, `127.0.0.1` is loopback inside the container. It would need to use `rdns=True` and `host=hasura`, since that is what the container is named in the docker-compose network. Alternatively, you can also set the containers to run with `--net=host`.

**Comment by temrix** [comment]
Thank you for the documentation. Glad to see that it is possible now!

**Comment by abn** [comment]
Closing this PR as this is no longer required. Feel free to contribute PRs/Issues as required.

**Pull request closed without merging**
